services:
  db:
    image: postgres:16
    container_name: ecotrack_db
    restart: always
    environment:
      POSTGRES_DB: ecotrack
      POSTGRES_USER: ecouser
      POSTGRES_PASSWORD: ecopass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: ecotrack_web
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_NAME: ecotrack
      DB_USER: ecouser
      DB_PASSWORD: ecopass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  pgdata:
